services:
  app:
    env_file: ".env"
    build: .
    ports:
      - "${UI_PORT}:${UI_PORT}"
    volumes:
      - ./src:/app/src  # mount source code
      - ./assets:/app/assets
      - ./config:/app/config
      - ./app.py:/app/app.py
    command: python app.py
    restart: on-failure
