{{- if .Values.app.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: "biasanalyzer-app"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          command:
            - gunicorn
            - app:server
            - --workers=2
            - --bind=0.0.0.0:8855
          ports:
            - containerPort: {{ .Values.service.port | int }}
              protocol: TCP
          env:
            - name: UI_PORT
              value: "{{ .Values.env.UI_PORT }}"
            - name: SESSION_SECRET_KEY
              value: "{{ .Values.env.SESSION_SECRET_KEY }}"
            - name: DEBUG
              value: {{ .Values.env.DEBUG | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: app-code
              mountPath: /app
      volumes:
        - name: app-code
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-app-pvc
{{- end }}