apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-app-pvc
  annotations:
    "helm.sh/resource-policy": "keep"
spec:
  storageClassName: basic
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
