replicaCount: 1

image:
  repository: "renci/ba_app"
  tag: "latest"
  pullPolicy: "IfNotPresent"

service:
  type: ClusterIP
  port: 8855

env:
  UI_PORT: "8855"
  DEBUG: "False"
  SESSION_SECRET_KEY: 'FILL_IN_A_SECRET_KEY'

gunicorn:
  workers: 2

resources:
  limits:
    cpu: "2"
    memory: "6Gi"
  requests:
    cpu: "2"
    memory: "6Gi"

preload:
  enabled: false
app:
  enabled: true

ingress:
  hosts:
    - host: ba-demo.apps.renci.org
      paths:
        - path: /
          pathType: ImplementationSpecific
          port: "8855"
  tls:
    - secretName: ba-demo.apps.renci.org-tls
      hosts:
        - ba-demo.apps.renci.org
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    cert-manager.io/cluster-issuer: letsencrypt

